logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:INFO}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
  level.org.apache.jena.riot: ERROR
  level.org.apache.kafka: ERROR
  level.io.confluent.kafka: ERROR
server:
  port: 8080
management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        info: ping
        health: ready
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: fdk-mqa-dcat-validator
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY:http://localhost:8081}
application:
  kafka:
    group-id: fdk-mqa-dcat-validator
    topics:
      dataset-events: mqa-dataset-events
      mqa-events: mqa-events
---
spring:
  config.activate.on-profile: develop
