---
apiVersion: v1
kind: Service
metadata:
  name: fdk-mqa-dcat-validator
spec:
  selector:
    app: fdk-mqa-dcat-validator
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
