/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.fdk.mqa;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum DatasetEventType {
  DATASET_HARVESTED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"DatasetEventType\",\"namespace\":\"no.fdk.mqa\",\"symbols\":[\"DATASET_HARVESTED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
