---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdk-mqa-dcat-validator
  labels:
    app: fdk-mqa-dcat-validator
spec:
  template:
    spec:
      containers:
        - name: fdk-mqa-dcat-validator
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: KAFKA_SCHEMA_REGISTRY
              valueFrom:
                secretKeyRef:
                  name: fdk-metadata-quality-staging
                  key: SCHEMA_REGISTRY
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: fdk-metadata-quality-staging
                  key: BROKERS
